# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Alan's ITP Blog
subtitle: ''
description: "Alan Ren's ITP documentation blogs for classes"
keywords:
author: Alan Ren
language: en
timezone: 'America/New_York'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://itp.alan.ooo
## This is not wrong!
permalink: :category/:title/
permalink_defaults:
  lang: en
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
relative_link: false
future: true
highlight:
  enable: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
  'Intro to Physical Computing': PComp
  'VisualLanguage': VisualLanguage
  'Intro to Computational Media': ICM
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
  - '.nojekyll'
  # Include 'source/css/_typing.css'.
  - 'css/_typing.css'
  # Include any file in 'source/_css/'.
  - '_css/*'
  # Include any file and subfolder in 'source/_css/'.
  - '_css/**/*'

exclude:
  # Exclude 'source/js/test.js'.
  - 'js/test.js'
  # Exclude any file in 'source/js/'.
  - 'js/*'
  # Exclude any file and subfolder in 'source/js/'.
  - 'js/**/*'
  # Exclude any file with filename that starts with 'test' in 'source/js/'.
  - 'js/test*'
  # Exclude any file with filename that starts with 'test' in 'source/js/' and its subfolders.
  - 'js/**/test*'
  # Do not use this to exclude posts in the 'source/_posts/'.
  # Use skip_render for that. Or prepend an underscore to the filename.
  # - "_posts/hello-world.md" # Does not work.

ignore:
  # Ignore any folder named 'foo'.
  - '**/foo'
  # Ignore 'foo' folder in 'themes/' only.
  - '**/themes/*/foo'
  # Same as above, but applies to every subfolders of 'themes/'.
  - '**/themes/**/foo'

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: aomori
# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/alanvww/ITP_blogs
  # example, https://github.com/hexojs/hexojs.github.io
  branch: gh-pages

# aomori settings
## Docs: https://aomori.linhong.me/v/chinese/features/theme
aomori_logo: /images/A.R - With Background - NYU.png
aomori_logo_typed_animated: false

aomori_widgets:
  - toc # 文章导航
  - category #文章分类
  - tag # 文章标签
  - recent_posts # 最新文章
  - archive #文章归档

aomori_favicon: 💜

aomori_social:
  - icon: logo-instagram
    url: https://www.instagram.com/alan.j.ren/
  - icon: person-circle-outline
    url: https://alan.ooo
  - icon: mail-outline
    url: mailto:alan.j.ren@pm.me
  - icon: call-outline
    url: tel:6464944949

aomori_disqus_shortname: 'itp-blog-1'
